-- MySQL Script generated by MySQL Workbench
-- 10/05/16 21:06:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema atividade6
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `atividade6` ;

-- -----------------------------------------------------
-- Schema atividade6
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atividade6` DEFAULT CHARACTER SET utf8 ;
USE `atividade6` ;

-- -----------------------------------------------------
-- Table `atividade6`.`registro_acesso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `atividade6`.`registro_acesso` ;

CREATE TABLE IF NOT EXISTS `atividade6`.`registro_acesso` (
  `NOME` TINYTEXT NULL DEFAULT NULL,
  `SOBRENOME` TINYTEXT NULL DEFAULT NULL,
  `EMAIL` TINYTEXT NULL DEFAULT NULL,
  `LOGIN` TINYTEXT NULL DEFAULT NULL,
  `IP` TINYTEXT NULL DEFAULT NULL,
  `NOME_EMPRESA` TINYTEXT NULL DEFAULT NULL,
  `DATA` DATETIME NULL DEFAULT NULL,
  `HORA` DATETIME NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
