-- MySQL Script generated by MySQL Workbench
-- 11/08/16 17:50:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`diretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diretor` (
  `id_diretor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_diretor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `indicador_sexo` INT NOT NULL,
  `indicador_violencia` INT NOT NULL,
  PRIMARY KEY (`id_genero`),
  UNIQUE INDEX `idgenero_UNIQUE` (`id_genero` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tempo` (
  `id_tempo` INT NOT NULL AUTO_INCREMENT,
  `ano` INT NOT NULL,
  `trimestre` INT NOT NULL,
  `mes` INT NOT NULL,
  `turno` VARCHAR(10) NULL,
  PRIMARY KEY (`id_tempo`),
  UNIQUE INDEX `idtempo_UNIQUE` (`id_tempo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`local` (
  `id_local` INT NOT NULL AUTO_INCREMENT,
  `regiao` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_local`),
  UNIQUE INDEX `idlocal_UNIQUE` (`id_local` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sala` (
  `id_sala` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sala`),
  UNIQUE INDEX `idsala_UNIQUE` (`id_sala` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exibicao_filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exibicao_filmes` (
  `id_diretor` INT NOT NULL,
  `id_local` INT NOT NULL,
  `id_genero` INT NOT NULL,
  `id_tempo` INT NOT NULL,
  `id_sala` INT NOT NULL,
  `quantidade_exibicoes` INT NOT NULL,
  PRIMARY KEY (`id_diretor`, `id_local`, `id_genero`, `id_tempo`, `id_sala`),
  INDEX `fk_exibicao_filmes_local1_idx` (`id_local` ASC),
  INDEX `fk_exibicao_filmes_genero1_idx` (`id_genero` ASC),
  INDEX `fk_exibicao_filmes_tempo1_idx` (`id_tempo` ASC),
  INDEX `fk_exibicao_filmes_sala1_idx` (`id_sala` ASC),
  CONSTRAINT `fk_exibicao_filmes_diretor`
    FOREIGN KEY (`id_diretor`)
    REFERENCES `mydb`.`diretor` (`id_diretor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exibicao_filmes_local1`
    FOREIGN KEY (`id_local`)
    REFERENCES `mydb`.`local` (`id_local`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exibicao_filmes_genero1`
    FOREIGN KEY (`id_genero`)
    REFERENCES `mydb`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exibicao_filmes_tempo1`
    FOREIGN KEY (`id_tempo`)
    REFERENCES `mydb`.`tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exibicao_filmes_sala1`
    FOREIGN KEY (`id_sala`)
    REFERENCES `mydb`.`sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
