-- MySQL Script generated by MySQL Workbench
-- 08/03/16 07:33:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema infoMind
-- -----------------------------------------------------
-- Banco de dados da aplicação InfoMind.

-- -----------------------------------------------------
-- Schema infoMind
--
-- Banco de dados da aplicação InfoMind.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `infoMind` DEFAULT CHARACTER SET utf8 ;
USE `infoMind` ;

-- -----------------------------------------------------
-- Table `infoMind`.`membro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoMind`.`membro` ;

CREATE TABLE IF NOT EXISTS `infoMind`.`membro` (
  `idMembro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `telefone` VARCHAR(15) NULL,
  `dataNasc` DATE NOT NULL,
  `isLider` VARCHAR(3) NOT NULL,
  `dataBatismo` DATE NOT NULL,
  `isDoze` VARCHAR(3) NOT NULL,
  `enderecoMembro` VARCHAR(70) NOT NULL,
  `bairroMembro` VARCHAR(70) NOT NULL,
  `cidadeMembro` VARCHAR(45) NOT NULL,
  `estadoMembro` CHAR(2) NOT NULL,
  `status` VARCHAR(3) NULL DEFAULT 'SIM',
  PRIMARY KEY (`idMembro`),
  UNIQUE INDEX `idmembro_UNIQUE` (`idMembro` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoMind`.`igreja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoMind`.`igreja` ;

CREATE TABLE IF NOT EXISTS `infoMind`.`igreja` (
  `idIgreja` INT NOT NULL AUTO_INCREMENT,
  `dataAbertura` DATE NOT NULL,
  `enderecoIgreja` VARCHAR(70) NOT NULL,
  `bairroIgreja` VARCHAR(70) NOT NULL,
  `cidadeIgreja` VARCHAR(45) NOT NULL,
  `estadoIgreja` CHAR(2) NOT NULL,
  `status` VARCHAR(3) NULL DEFAULT 'SIM',
  PRIMARY KEY (`idIgreja`),
  UNIQUE INDEX `idigreja_UNIQUE` (`idIgreja` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoMind`.`culto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoMind`.`culto` ;

CREATE TABLE IF NOT EXISTS `infoMind`.`culto` (
  `idCulto` INT NOT NULL AUTO_INCREMENT,
  `dataCelebracao` DATE NOT NULL,
  `qtdMembro` INT NOT NULL DEFAULT 0,
  `qtdVisitante` INT NOT NULL DEFAULT 0,
  `qtdConversao` INT NOT NULL DEFAULT 0,
  `horario` TIME NOT NULL,
  `descricaoCulto` VARCHAR(100) NULL,
  `idIgrejaCulto` INT NOT NULL,
  PRIMARY KEY (`idCulto`),
  UNIQUE INDEX `idculto_UNIQUE` (`idCulto` ASC),
  INDEX `fk_culto_igreja1_idx` (`idIgrejaCulto` ASC),
  CONSTRAINT `id_igreja_fk`
    FOREIGN KEY (`idIgrejaCulto`)
    REFERENCES `infoMind`.`igreja` (`idIgreja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoMind`.`cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoMind`.`cargo` ;

CREATE TABLE IF NOT EXISTS `infoMind`.`cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCargo`),
  UNIQUE INDEX `idcargo_UNIQUE` (`idCargo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoMind`.`celula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoMind`.`celula` ;

CREATE TABLE IF NOT EXISTS `infoMind`.`celula` (
  `idCelula` INT NOT NULL AUTO_INCREMENT,
  `diaRealizacao` VARCHAR(10) NOT NULL,
  `horario` TIME NOT NULL,
  `idMembroLider` INT NOT NULL,
  `enderecoCelula` VARCHAR(70) NOT NULL,
  `bairroCelula` VARCHAR(70) NOT NULL,
  `cidadeCelula` VARCHAR(45) NOT NULL,
  `estadoCelula` CHAR(2) NOT NULL,
  `status` VARCHAR(3) NULL DEFAULT 'SIM',
  PRIMARY KEY (`idCelula`),
  UNIQUE INDEX `idcelula_UNIQUE` (`idCelula` ASC),
  INDEX `fk_celula_membro1_idx` (`idMembroLider` ASC),
  CONSTRAINT `fk_celula_membro1`
    FOREIGN KEY (`idMembroLider`)
    REFERENCES `infoMind`.`membro` (`idMembro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoMind`.`posse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoMind`.`posse` ;

CREATE TABLE IF NOT EXISTS `infoMind`.`posse` (
  `idCargoPosse` INT NOT NULL,
  `idMembroPosse` INT NOT NULL,
  `dataPosse` DATE NOT NULL,
  `dataFimPosse` DATE NULL,
  `idIgrejaPosse` INT NOT NULL,
  PRIMARY KEY (`idCargoPosse`, `idMembroPosse`, `dataPosse`),
  INDEX `fk_Posse_membro1_idx` (`idMembroPosse` ASC),
  INDEX `fk_Posse_igreja1_idx` (`idIgrejaPosse` ASC),
  CONSTRAINT `fk_Posse_cargo1`
    FOREIGN KEY (`idCargoPosse`)
    REFERENCES `infoMind`.`cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posse_membro1`
    FOREIGN KEY (`idMembroPosse`)
    REFERENCES `infoMind`.`membro` (`idMembro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posse_igreja1`
    FOREIGN KEY (`idIgrejaPosse`)
    REFERENCES `infoMind`.`igreja` (`idIgreja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoMind`.`discipulado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoMind`.`discipulado` ;

CREATE TABLE IF NOT EXISTS `infoMind`.`discipulado` (
  `idMembroDiscipulador` INT NOT NULL,
  `idMembroDiscipulo` INT NOT NULL,
  `dataInicioDiscipulado` DATE NOT NULL,
  `dataFimDiscipulado` DATE NULL,
  PRIMARY KEY (`idMembroDiscipulador`, `idMembroDiscipulo`, `dataInicioDiscipulado`),
  INDEX `fk_discipulador_membro2_idx` (`idMembroDiscipulo` ASC),
  CONSTRAINT `fk_discipulador_membro1`
    FOREIGN KEY (`idMembroDiscipulador`)
    REFERENCES `infoMind`.`membro` (`idMembro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discipulador_membro2`
    FOREIGN KEY (`idMembroDiscipulo`)
    REFERENCES `infoMind`.`membro` (`idMembro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoMind`.`responsabilidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoMind`.`responsabilidade` ;

CREATE TABLE IF NOT EXISTS `infoMind`.`responsabilidade` (
  `idIgrejaResp` INT NOT NULL,
  `idMembroResp` INT NOT NULL,
  `dataInicioResp` DATE NOT NULL,
  `dataFimResp` DATE NULL,
  PRIMARY KEY (`idIgrejaResp`, `idMembroResp`, `dataInicioResp`),
  INDEX `fk_igreja_has_membro_membro1_idx` (`idMembroResp` ASC),
  INDEX `fk_igreja_has_membro_igreja1_idx` (`idIgrejaResp` ASC),
  CONSTRAINT `fk_igreja_has_membro_igreja1`
    FOREIGN KEY (`idIgrejaResp`)
    REFERENCES `infoMind`.`igreja` (`idIgreja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_igreja_has_membro_membro1`
    FOREIGN KEY (`idMembroResp`)
    REFERENCES `infoMind`.`membro` (`idMembro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoMind`.`membresia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoMind`.`membresia` ;

CREATE TABLE IF NOT EXISTS `infoMind`.`membresia` (
  `idIgrejaMembro` INT NOT NULL,
  `idMembroIgreja` INT NOT NULL,
  `dataInicioMembresia` DATE NOT NULL,
  `dataFimMembresia` DATE NULL,
  PRIMARY KEY (`idIgrejaMembro`, `idMembroIgreja`, `dataInicioMembresia`),
  INDEX `fk_igreja_has_membro_membro2_idx` (`idMembroIgreja` ASC),
  INDEX `fk_igreja_has_membro_igreja2_idx` (`idIgrejaMembro` ASC),
  CONSTRAINT `fk_igreja_has_membro_igreja2`
    FOREIGN KEY (`idIgrejaMembro`)
    REFERENCES `infoMind`.`igreja` (`idIgreja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_igreja_has_membro_membro2`
    FOREIGN KEY (`idMembroIgreja`)
    REFERENCES `infoMind`.`membro` (`idMembro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `infoMind`.`porte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `infoMind`.`porte` ;

CREATE TABLE IF NOT EXISTS `infoMind`.`porte` (
  `idIgrejaPorte` INT NOT NULL,
  `idCelulaPorte` INT NOT NULL,
  `dataInicioCelula` DATE NOT NULL,
  `dataFimCelula` DATE NULL,
  PRIMARY KEY (`idIgrejaPorte`, `idCelulaPorte`, `dataInicioCelula`),
  INDEX `fk_igreja_has_celula_celula1_idx` (`idCelulaPorte` ASC),
  INDEX `fk_igreja_has_celula_igreja1_idx` (`idIgrejaPorte` ASC),
  CONSTRAINT `fk_igreja_has_celula_igreja1`
    FOREIGN KEY (`idIgrejaPorte`)
    REFERENCES `infoMind`.`igreja` (`idIgreja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_igreja_has_celula_celula1`
    FOREIGN KEY (`idCelulaPorte`)
    REFERENCES `infoMind`.`celula` (`idCelula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
